# Generated by Django 2.2.4 on 2021-05-18 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('time_spent', models.CharField(max_length=500)),
                ('no_of_words', models.CharField(max_length=500)),
                ('rating', models.CharField(max_length=500)),
                ('vector', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
