# Generated by Django 3.2 on 2021-05-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0002_recommended_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation_Data',
        ),
    ]
