# Generated by Django 3.2 on 2021-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0003_delete_recommendation_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_data',
            name='recommended_text',
            field=models.TextField(default='nthg'),
        ),
        migrations.AlterField(
            model_name='recommended_data',
            name='user_vector',
            field=models.TextField(default='nthg'),
        ),
    ]
